export type Category = "common" | "pollution" | "sport";
export interface Card { word: string; definition: string }
export const categories: Category[] = ["common", "pollution", "sport"];
export const vocabulary: Record<Category, Card[]> = {
  common: [
    { word: "to bring", definition: "przynieść" },
    { word: "to manage", definition: "zdołać" },
    { word: "to predict", definition: "przewidywać" },
    { word: "to say", definition: "mówić" },
    { word: "to make", definition: "robić" },
    { word: "to know", definition: "wiedzieć" },
    { word: "to come", definition: "przyjść" },
    { word: "to find", definition: "znaleźć" },
    { word: "to call", definition: "dzwonić" },
    { word: "to play", definition: "grać" },
  ],
  pollution: [
    { word: "acid", definition: "kwas" },
    { word: "petrol", definition: "benzyna" },
    { word: "dioxide", definition: "dwutlenek" },
    { word: "sulpour", definition: "siarka" },
    { word: "soot", definition: "sadza" },
    { word: "exhaust", definition: "spaliny" },
    { word: "harmful", definition: "szkodliwy" },
    { word: "monoxide", definition: "tlenek" },
    { word: "nitrogen", definition: "azot" },
    { word: "particule", definition: "cząsteczka" },
  ],
  sport: [
    { word: "archery", definition: "łucznictwo" },
    { word: "basketball", definition: "koszykówka" },
    { word: "coach", definition: "trener" },
    { word: "draw", definition: "remis" },
    { word: "fencing", definition: "szermierka" },
    { word: "goalkeeper", definition: "bramkarz" },
    { word: "net", definition: "siatka" },
    { word: "pole vault", definition: "skok o tyczce" },
    { word: "racket", definition: "rakieta" },
    { word: "relay", definition: "sztafeta" },
  ],
};
const translations: {pl: string; de: string}[] = [
    { pl: "skok o tyczce", de: "Stabhochsprung" },
    { pl: "przewidywać", de: "vorhersagen" },
    { pl: "przewidzieć", de: "vorhersagen" },
    { pl: "szkoleniowiec", de: "Coach" },
    { pl: "przynieść", de: "bringen" },
    { pl: "koszykówka", de: "Basketball" },
    { pl: "łucznictwo", de: "Bogenschießen" },
    { pl: "szermierka", de: "Fechten" },
    { pl: "bramkarz", de: "Torwart" },
    { pl: "szkodliwy", de: "schädlich" },
    { pl: "cząsteczka", de: "Teilchen" },
    { pl: "dwutlenek", de: "Dioxid" },
    { pl: "spaliny", de: "Abgase" },
    { pl: "siarka", de: "Schwefel" },
    { pl: "benzyna", de: "Benzin" },
    { pl: "tlenek", de: "Oxid" },
    { pl: "tlen", de: "Sauerstoff" },
    { pl: "sadza", de: "Ruß" },
    { pl: "azot", de: "Stickstoff" },
    { pl: "kwas", de: "Säure" },
    { pl: "baseball", de: "Baseball" },
    { pl: "trener", de: "Trainer" },
    { pl: "sędzia", de: "Schiedsrichter" },
    { pl: "remis", de: "Unentschieden" },
    { pl: "przerwa", de: "Pause" },
    { pl: "siatka", de: "Netz" },
    { pl: "sztafeta", de: "Staffel" },
    { pl: "rakieta", de: "Schläger" },
    { pl: "kosz", de: "Korb" },
    { pl: "boks", de: "Boxen" },
    { pl: "zdołać", de: "schaffen" },
    { pl: "znaleźć", de: "finden" },
    { pl: "dzwonić", de: "anrufen" },
    { pl: "mówić", de: "sagen" },
    { pl: "wiedzieć", de: "wissen" },
    { pl: "przyjść", de: "kommen" },
    { pl: "robić", de: "machen" },
    { pl: "zrobić", de: "machen" },
    { pl: "grać", de: "spielen" },
    { pl: "udawać", de: "vortäuschen" },
  ];
export function definitionFor(card: Card, language: string): string {
  return language === "de" ? translations.find(entry => entry.pl === card.definition)?.de ?? card.definition : card.definition;
}
