export type Category = 'common' | 'pollution' | 'sport';
export type Language = 'pl' | 'en' | 'de';
export interface Card { word: string; definition: string; }
export const vocabulary: Record<Category, Card[]> = {
  common: [
    { word: "to bring", definition: "przynieść" },
    { word: "to manage", definition: "zdołać" },
    { word: "to predict", definition: "przewidywać" },
    { word: "to say", definition: "mówić" },
    { word: "to make", definition: "robić" },
    { word: "to know", definition: "wiedzieć" },
    { word: "to come", definition: "przyjść" },
    { word: "to find", definition: "znaleźć" },
    { word: "to call", definition: "dzwonić" },
    { word: "to play", definition: "grać" },
  ],
  pollution: [
    { word: "acid", definition: "kwas" },
    { word: "petrol", definition: "benzyna" },
    { word: "dioxide", definition: "dwutlenek" },
    { word: "sulpour", definition: "siarka" },
    { word: "soot", definition: "sadza" },
    { word: "exhaust", definition: "spaliny" },
    { word: "harmful", definition: "szkodliwy" },
    { word: "monoxide", definition: "tlenek" },
    { word: "nitrogen", definition: "azot" },
    { word: "particule", definition: "cząsteczka" },
  ],
  sport: [
    { word: "archery", definition: "łucznictwo" },
    { word: "basketball", definition: "koszykówka" },
    { word: "coach", definition: "trener" },
    { word: "draw", definition: "remis" },
    { word: "fencing", definition: "szermierka" },
    { word: "goalkeeper", definition: "bramkarz" },
    { word: "net", definition: "siatka" },
    { word: "pole vault", definition: "skok o tyczce" },
    { word: "racket", definition: "rakieta" },
    { word: "relay", definition: "sztafeta" },
  ],
};
export const translations = [
    { pl: "pojęcia i fiszki", en: "terms and flashcards", de: "Begriffe und Karteikarten" },
    { pl: "SPACJA = DEFINICJA", en: "SPACE = DEFINITION", de: "LEERTASTE = DEFINITION" },
    { pl: "WSTECZ", en: "BACK", de: "ZURÜCK" },
    { pl: "DALEJ", en: "NEXT", de: "WEITER" },
    {
      pl: "4 pojęcia pojęć ze wszystkich kategorii",
      en: "4 terms from all categories",
      de: "4 Begriffe aus allen Kategorien",
    },
    {
      pl: "wybierz kategorię i naciśnij na pole",
      en: "select a category and click the card",
      de: "Kategorie wählen und auf die Karte klicken",
    },
    {
      pl: "Liczba poprawnych odpowiedzi",
      en: "Correct answers",
      de: "Richtige Antworten",
    },
    {
      pl: "pollution -pojęcia i definicje",
      en: "pollution - terms and definitions",
      de: "pollution - Begriffe und Definitionen",
    },
    {
      pl: "pojęcia i definicje",
      en: "terms and definitions",
      de: "Begriffe und Definitionen",
    },
    {
      pl: "udzielona odpowiedz",
      en: "answer given",
      de: "gegebene Antwort",
    },
    {
      pl: "pojęcie -> definicja",
      en: "term -> definition",
      de: "Begriff -> Definition",
    },
    { pl: "wybierz kategorię", en: "select a category", de: "Kategorie wählen" },
    { pl: "niepoprawna", en: "incorrect", de: "falsch" },
    { pl: "modyfikacje", en: "modifications", de: "Änderungen" },
    { pl: "Zatwierdź", en: "Submit", de: "Bestätigen" },
    { pl: "Poprzednia", en: "Previous", de: "Zurück" },
    { pl: "Następna", en: "Next", de: "Weiter" },
    { pl: "odpowiedź", en: "answer", de: "Antwort" },
    { pl: "poprawna", en: "correct", de: "richtig" },
    { pl: "kategorie", en: "categories", de: "Kategorien" },
    { pl: "Fiszki", en: "Flashcards", de: "Karteikarten" },
    { pl: "pojęcia", en: "terms", de: "Begriffe" },
    { pl: "resetuj", en: "reset", de: "zurücksetzen" },
    { pl: "Treść", en: "Content", de: "Inhalt" },
    { pl: "była", en: "was", de: "war" },
  ];
export const vocabularyTranslations = [
    { pl: "skok o tyczce", de: "Stabhochsprung" },
    { pl: "przewidywać", de: "vorhersagen" },
    { pl: "przewidzieć", de: "vorhersagen" },
    { pl: "szkoleniowiec", de: "Coach" },
    { pl: "przynieść", de: "bringen" },
    { pl: "koszykówka", de: "Basketball" },
    { pl: "łucznictwo", de: "Bogenschießen" },
    { pl: "szermierka", de: "Fechten" },
    { pl: "bramkarz", de: "Torwart" },
    { pl: "szkodliwy", de: "schädlich" },
    { pl: "cząsteczka", de: "Teilchen" },
    { pl: "dwutlenek", de: "Dioxid" },
    { pl: "spaliny", de: "Abgase" },
    { pl: "siarka", de: "Schwefel" },
    { pl: "benzyna", de: "Benzin" },
    { pl: "tlenek", de: "Oxid" },
    { pl: "tlen", de: "Sauerstoff" },
    { pl: "sadza", de: "Ruß" },
    { pl: "azot", de: "Stickstoff" },
    { pl: "kwas", de: "Säure" },
    { pl: "baseball", de: "Baseball" },
    { pl: "trener", de: "Trainer" },
    { pl: "sędzia", de: "Schiedsrichter" },
    { pl: "remis", de: "Unentschieden" },
    { pl: "przerwa", de: "Pause" },
    { pl: "siatka", de: "Netz" },
    { pl: "sztafeta", de: "Staffel" },
    { pl: "rakieta", de: "Schläger" },
    { pl: "kosz", de: "Korb" },
    { pl: "boks", de: "Boxen" },
    { pl: "zdołać", de: "schaffen" },
    { pl: "znaleźć", de: "finden" },
    { pl: "dzwonić", de: "anrufen" },
    { pl: "mówić", de: "sagen" },
    { pl: "wiedzieć", de: "wissen" },
    { pl: "przyjść", de: "kommen" },
    { pl: "robić", de: "machen" },
    { pl: "zrobić", de: "machen" },
    { pl: "grać", de: "spielen" },
    { pl: "udawać", de: "vortäuschen" },
  ];
